name: Continuous integration (CI) testing

on: [push, pull_request]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    container: node:lts-buster
    strategy:
      # Use current LTS, previous LTS and latest versions of Node.js
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Codecov reporting needs fetch-depth > 1
        fetch-depth: 2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Run tests
      run: npm test
    - name: Report code coverage
      uses: codecov/codecov-action@v1
